/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EmojiView: typeof import('./components/chat/emojiView.vue')['default']
    LoginInput: typeof import('./components/input/loginInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/search/search.vue')['default']
    Tabbar: typeof import('./components/tabbar/index.vue')['default']
  }
}
